### ISSUE TITLE
e4e.onnx

### ISSUE THREAD

**Issue by johndpope** [Crosser-XDU/WebProjectOfStyleClip#2]
any guidance on where to find or build this?

**Comment by Crosser-XDU** [comment]
Sorry for answering so late！This is a model map that is created by onnxruntime(a useful framework for inferencing ) for a purpose of making the inferencing time more short。I forgot to introduce it on the README，thank you for your question。



---- Replied Message ----
| From | John D. ***@***.***> |
| Date | 08/29/2022 08:04 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [Crosser-XDU/WebProjectOfStyleClip] e4e.onnx (Issue #2) |

any guidance on where to find or build this?

**Comment by johndpope** [comment]
thx
